CREATE DATABASE TodoList;

GO

USE TodoList;

CREATE TABLE Customers (
	Id int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FirstName VARCHAR(60) NOT NULL,
	LastName VARCHAR(60) NOT NULL,
	Birthday DATE NOT NULL
);


CREATE TABLE Contacts (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Type VARCHAR(10) NOT NULL,
	Value VARCHAR(100) NOT NULL,
	CustomerId INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES Customers(Id)
);

CREATE TABLE Tasks (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Description NVARCHAR(1000) NOT NULL,
	CreationDate DATETIME NOT NULL,
	Solved BIT NOT NULL,
	CustomerId INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES Customers(Id)
);